import { StyleSheet } from "react-native";
import { colors, fontSize, sizes } from "../../services";
export const styles = StyleSheet.create({
  MainContainer: {
    backgroundColor: colors.white,
    height: sizes.screenHeight,
    width: sizes.screenWidth,
  },
  row: {
    flexDirection: "row",
    position: "absolute",
    right: sizes.screenWidth * 0.05,
    top: sizes.screenHeight * 0.03,
    justifyContent: "space-between",
    width: sizes.screenWidth * 0.15,
  },
  imgSty: {
    resizeMode: "contain",
    width: sizes.screenWidth * 0.06,
    height: sizes.screenHeight * 0.04,
    // position:'absolute'
    // backgroundColor:'red'
  },
  columnView: {
    color: colors.disabledBg3,
    alignSelf: "center",
  },
  columnView2: {
    color: colors.disabledBg3,
    alignSelf: "center",
    marginTop: sizes.screenHeight * 0.03,
  },
  center: {
    alignSelf: "center",
  },
  messageBlackImg: {
    width: sizes.screenWidth * 0.57,
    height: sizes.screenHeight * 0.078,
    alignSelf: "flex-end",
    marginTop: sizes.screenHeight * 0.02,
    // alignItems: 'flex-end',
    // justifyContent: 'center',
  },
  messageBlackImg2: {
    width: sizes.screenWidth * 0.6,
    height: sizes.screenHeight * 0.1,
    alignSelf: "flex-end",
    marginTop: sizes.screenHeight * 0.02,
    // alignItems: 'flex-end',
    // justifyContent: 'center',
  },
  textWhite: {
    color: "white",
    textAlign: "right",
    marginRight: sizes.screenWidth * 0.06,
    marginTop: sizes.screenHeight * 0.02,
  },
  textWhite2: {
    color: "white",
    textAlign: "right",
    marginRight: sizes.screenWidth * 0.08,
    marginTop: sizes.screenHeight * 0.02,
    // marginLeft: sizes.screenWidth * 0.021,
  },
  messageWhiteImg: {
    width: sizes.screenWidth * 0.78,
    height: sizes.screenHeight * 0.077,
    // alignSelf: ',
  },
  messageWhiteImg2: {
    width: sizes.screenWidth * 0.65,
    height: sizes.screenHeight * 0.077,
    marginTop: sizes.screenHeight * 0.02,
    // alignSelf: ',
  },
  messageTextBlack: {
    color: colors.black,
    padding: sizes.screenWidth * 0.02,
    marginLeft: sizes.screenWidth * 0.035,
  },
  messageTextBlack2: {
    color: colors.black,
    marginTop: sizes.screenHeight * 0.02,
    marginLeft: sizes.screenWidth * 0.05,
  },
  chatView: {
    flexDirection: "column",
    paddingHorizontal: 25,
    height: sizes.screenHeight * 0.85,
    flexDirection: "column",
    justifyContent: "flex-end",
  },
  reqView: {
    width: sizes.screenWidth * 0.85,
    alignSelf: "center",
    alignItems: "center",
    bottom: sizes.screenHeight * 0.65,
  },
  confirmReqBtn: {
    color: colors.white,
    backgroundColor: "#3A955E",
    paddingHorizontal: sizes.screenWidth * 0.05,
    paddingVertical: sizes.screenHeight * 0.01,
    borderRadius: sizes.screenWidth * 0.05,
    fontWeight: "500",
  },
  declineBtn: {
    color: colors.white,
    backgroundColor: "#BC101A",
    paddingHorizontal: sizes.screenWidth * 0.05,
    paddingVertical: sizes.screenHeight * 0.01,
    borderRadius: sizes.screenWidth * 0.05,
    fontWeight: "500",
  },
  lastView: {
    width: sizes.screenWidth * 0.9,

    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: sizes.screenHeight * 0.01,
    paddingBottom: sizes.screenHeight * 0.005,
  },
  clipImg: {
    height: sizes.screenHeight * 0.059,
    width: sizes.screenWidth * 0.11,
  },
  input: {
    backgroundColor: "white",
    width: sizes.screenWidth * 0.62,
    borderRadius: sizes.screenWidth * 0.06,
    paddingLeft: sizes.screenWidth * 0.05,
    color: colors.black,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,

    elevation: 3,
  },
  mainModal: {
    backgroundColor: "white",
    height: sizes.screenHeight * 0.35,
    borderTopRightRadius: sizes.screenWidth * 0.08,
    borderTopLeftRadius: sizes.screenWidth * 0.08,
    width: sizes.screenWidth,
    alignSelf: "center",
    marginTop: sizes.screenHeight * 0.68,
  },
  modalFirstView: {
    alignSelf: "center",
    alignItems: "center",
    marginTop: sizes.screenHeight * 0.033,
    marginBottom: sizes.screenHeight * 0.01,
  },
  modalFirstViewText: {
    fontSize: fontSize.large,
    color: "#F56666",
    fontWeight: "bold",
  },
  modalText: {
    fontSize: fontSize.large,
    color: colors.black,
    fontWeight: "bold",
    marginTop: sizes.screenHeight * 0.02,
    width: sizes.screenWidth * 0.7,
    textAlign: "center",
  },
  subText: {
    color: colors.black,
    textAlign: "center",
    width: sizes.screenWidth * 0.8,
    marginTop: sizes.screenHeight * 0.02,
  },
  modalSecondView: {
    flexDirection: "row",
    alignSelf: "center",
    marginTop: sizes.screenHeight * 0.02,
  },
  modalBtn: {
    color: colors.black,
    fontSize: fontSize.medium,
    fontWeight: "bold",
  },
  modalBtn1: {
    color: colors.white,
    fontSize: fontSize.medium,
    fontWeight: "bold",
  },
  modalBtnView: {
    width: sizes.screenWidth * 0.45,
    height: sizes.screenWidth * 0.12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderRadius: sizes.screenHeight * 0.05,
  },
  modalBtnView1: {
    backgroundColor: colors.black,
    width: sizes.screenWidth * 0.45,
    height: sizes.screenWidth * 0.12,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: sizes.screenWidth * 0.02,
    borderRadius: sizes.screenWidth * 0.06,
  },
  line: {
    height: 1,
    width: sizes.screenWidth * 0.82,
    backgroundColor: "#C4C4C4",
    marginTop: sizes.screenHeight * 0.02,
  },
});
